# Generated by Django 3.0.11 on 2020-12-24 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Text of comment')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
            ],
        ),
        migrations.CreateModel(
            name='LogTimeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_logged', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of logging')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('short_name', models.CharField(max_length=4, verbose_name='Short name')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Description')),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date start')),
                ('date_finish', models.DateTimeField(blank=True, null=True, verbose_name='Date finish')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_number', models.CharField(max_length=20, verbose_name='Number of task')),
                ('name', models.CharField(max_length=255, verbose_name='Name of task')),
                ('description', models.TextField(blank=True, max_length=5000, verbose_name='Description')),
                ('status', models.CharField(choices=[('BL', 'BACKLOG'), ('IP', 'IN_PROGRESS'), ('PP', 'POSTPONED'), ('DN', 'DONE'), ('ID', 'IS_DELAYED'), ('LT', 'BEING_LATE'), ('RV', 'REVIEW'), ('CL', 'CLOSED')], default='BL', max_length=2)),
                ('type', models.CharField(choices=[('WI', 'Work item'), ('BUG', 'Bug'), ('REQ', 'Requirement'), ('TT', 'Test'), ('KI', 'Know issue')], default='WI', max_length=3)),
                ('acceptance_criteria', models.TextField(blank=True, max_length=2000, verbose_name='Acceptance criteria')),
                ('priority', models.CharField(choices=[('HG', 'HIGH'), ('MD', 'MEDIUM'), ('LW', 'LOW')], default='MD', max_length=3)),
                ('estimate_hours', models.IntegerField(blank=True, null=True, verbose_name='Estimate task in hours')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('date_modified', models.DateTimeField(blank=True, null=True, verbose_name='Modification date')),
                ('deadline_date', models.DateTimeField(blank=True, null=True, verbose_name='Deadline date')),
            ],
        ),
    ]
