# Generated by Django 3.0.11 on 2020-12-24 18:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_auto_20201224_1938'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectmembership',
            unique_together={('project', 'member')},
        ),
    ]
