# Generated by Django 3.0.11 on 2020-12-24 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20201224_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='parent_task',
        ),
        migrations.CreateModel(
            name='TasksRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.IntegerField(choices=[(0, 'блокируется'), (1, 'блокирует'), (2, 'имеет дубль'), (3, 'дублирует'), (4, 'связана'), (90, 'описана тест-кейсом'), (91, 'покрывает требования')])),
                ('from_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_tasks', to='tasks.Task')),
                ('to_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_tasks', to='tasks.Task')),
            ],
        ),
    ]
