# Generated by Django 3.0.11 on 2020-12-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20201225_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtimetask',
            name='hours',
            field=models.FloatField(default=0.0),
        ),
    ]
