# Generated by Django 3.0.11 on 2020-12-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_logtimetask_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('BL', 'BACKLOG'), ('IP', 'IN_PROGRESS'), ('PP', 'POSTPONED'), ('DN', 'DONE'), ('ID', 'IS_DELAYED'), ('LT', 'BEING_LATE'), ('RV', 'REVIEW')], default='BL', max_length=2),
        ),
    ]
