# Generated by Django 3.0.11 on 2020-12-22 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_comment_logtimetask_participant_prioritytask_project_relationtask_role_statustask_task_typerelationt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Members of project')),
            ],
        ),
        migrations.RemoveField(
            model_name='relationtask',
            name='first_task',
        ),
        migrations.RemoveField(
            model_name='relationtask',
            name='second_task',
        ),
        migrations.RemoveField(
            model_name='relationtask',
            name='type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_tasks', to='users.Task', verbose_name='Parent task'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_finish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date finish'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date start'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('HG', 'HIGH'), ('MD', 'MEDIUM'), ('LW', 'LOW')], default='MD', max_length=3),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('BL', 'BACKLOG'), ('IP', 'IN_PROGRESS'), ('PP', 'POSTPONED'), ('DN', 'DONE'), ('ID', 'IS_DELAYED'), ('LT', 'BEING_LATE'), ('RV', 'REVIEW'), ('CL', 'CLOSED')], default='BL', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('WI', 'Work item'), ('BUG', 'Bug'), ('REQ', 'Requirement'), ('TT', 'Test'), ('KI', 'Know issue')], default='WI', max_length=3),
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='PriorityTask',
        ),
        migrations.DeleteModel(
            name='RelationTask',
        ),
        migrations.DeleteModel(
            name='StatusTask',
        ),
        migrations.DeleteModel(
            name='TypeTask',
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users.Project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='users.Role', verbose_name='Role of member'),
        ),
    ]
