# Generated by Django 3.0.11 on 2020-12-24 16:54

from django.db import migrations


def add_roles(apps, schema_editor):
    # We can't import the Role model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Role = apps.get_model('users', 'Role')

    roles = [
        Role(name="Проектный менеджер"),
        Role(name="Аналитик"),
        Role(name="Ответственный за качество"),
        Role(name="Лидер разработчиков"),
        Role(name="Тестировщик"),
        Role(name="Разработчик"),
    ]
    Role.objects.bulk_create(roles)


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20201224_1952'),
    ]

    operations = [
        migrations.RunPython(
            add_roles,
            reverse_code=migrations.RunPython.noop
        )
    ]
