# Generated by Django 3.0.11 on 2020-12-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='abbreviation',
            field=models.CharField(blank=True, db_index=True, max_length=3, verbose_name='Abbreviation'),
        ),
    ]
